### ISSUE TITLE
Transaction Interface Enum values (and others) are exposed as Unions

### ISSUE THREAD

**Issue by Thoruun** [Increase/increase-node#786]
Hi! The current Transaction interface in the SDK uses union types for properties that would be better represented as enums. This makes the code more difficult to maintain and weakens type checking. For example:

The currency property is defined as a union of string literals ('CAD' | 'CHF' | 'EUR' | 'GBP' | 'JPY' | 'USD') rather than an enum
The route_type property uses a union type ('account_number' | 'card' | 'lockbox' | null)
Similarly, the Transaction.Source.category property is implemented as a union type

Would it be possible to generate the SDK using TypeScript enums for these properties instead? This would improve type safety and make the interface more maintainable."

**Comment by sloanesturz** [comment]
Hi @Thoruun! Thank you for trying out the SDK and this helpful feedback!

This would be a breaking change for current users of the SDK, so I'd like to dig in a bit more and understand how an enum will improve the developer experience in your workflow.

Can you describe the operations you're trying to do where you'd want an enum? I included a code block below of how I reference string enums in our Typescript code internally.

```
interface Account {
    status: 'open' | 'closed'
}

const isAccountOk = (status: Account['status']): boolean => status === 'open'
```

**Comment by Thoruun** [comment]
Hi @sloanesturz, I think your example with Account using enums would be something like this:

```
enum AccountStatus {
  OPEN = 'open',
  CLOSED = 'closed'
}

interface Account {
    status: AccountStatus
}
```
Usage:
```
const newAccount =  await increase.accounts.retrieve();

if (newAccount.status === AccountStatus.OPEN) {
...
} 
```
Or with `switch`:

```
const newAccount =  await increase.accounts.retrieve();

switch (newAccount.status) {
 case AccountStatus.OPEN {
  ...
 }
break;
case  AccountStatus.CLOSED {
 ...
}
default: 
  throw new Error("Unknown account status");

```
To me this would provide a much cleaner and type safe interface into Increase system.

**Comment by sloanesturz** [comment]
I hear you! I agree it's a bit different that we don't generate an `AccountStatus` -- it's a stylistic choice in the design of this node package.

Take a look at this example -- it demonstrates how I'd recommend using the package currently, and how it'll point out to you the different types of errors you'd commonly run into while developing.

https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgIIIQewK7mQbwChkTkBnMOMbMgLmQHJMAHCEB5AH0YQBtMyEACYNCAX0KEwAT1ZoMOcAGVK1MsgC88rLjABtBhSo0GAXUlYQFZEIgBbTFbBQqEAOqYoAa1ABzTcgAFIg64PTooWAAlPQARpiYvBBwIJoAfATE5ADuwGAIABbBCroAdEZqUZmkyAhwgowsbAy0WTVQENRQqfC8gm219SgMfALCLQMkHV2pztgQWRIShJbWtg5OLpAAogAeznABxZHhJeAxyPGJyakaGUQkZLn5RSGKYOWqNFUPpHUNTFY7FaNSmnWw3WQvX6NX+w1GghEINB0whsyg8wGcMYZEwdk6BT8AH0IH0IC1kAB6SnICC7VgISBCWlQKCeSbIVGQ6ELEhLSQrRxrexCg6QACywDIZD8RzeulOkQuVySKXSBCpNLpDKZLLZUCyTzyhWO70+xjIPyxQ0aQImoM54O5cDJi3EQA

**Comment by Thoruun** [comment]
Thanks, this kinda would work, still doesn't seem straight and having basically a hardcoded strings in the project is not fun, but OK. Personally, I would prefer with cleaner enum interfaces.

**Comment by sloanesturz** [comment]
Thanks for bringing it up! It's a pretty divisive topic in the Typescript community [0], but we think the more idiomatic pattern at the moment is union types over enums. We'll probably stick with unions for the time being.

Appreciate you kicking the tires!

0. https://www.typescriptcourse.com/string-literal-unions-over-enums
